config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'
  get '/user' => "pages#minha", as: :user_root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :candidatos, only: [:index, :show] do
    resources :marcados, only: [:create]
  end
  resources :marcados, only: [:update]
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image:
linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)),
url(https://res.cloudinary.com/doewgeg5j/image/upload/v1636382044/production/Repolitiks/Banner/congresso-02_fusvev.jpg);">
  <div class="container">
    <h1>Repensar, refletir, reconsiderar, refazer, ressignificar... a política!</h1>
    <p>Acompanhe e monitore os políticos de seu interesse</p>
    <% if !user_signed_in? %>
      <%# <%= link_to "Quero Repolitizar", new_user_registration_path, class:"btn btn-primary" %>
    <% end %>
  </div>
  <div class="container text-center py-5">
    <%= form_tag candidatos_path, method: :get do %>
      <h6><span style="color:white">Digite o nome, cargo, partido ou UF de um político</span></h6>
      <div class="banner-form">
        <%= text_field_tag :query, params[:query], placeholder: "Todos os políticos", class: 'w-100 h-100 bg-white banner-input pl-3' %>
        <%= submit_tag "Repolitizar", class: "banner-btn btn btn-gradient" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_card_candidato.html.erb
<%# <div class="card-candidato flex-grow-1"> %>
<div class="card-candidato">
  <%# <%= link_to candidato_path(candidato), class:"link-candidato stretched-link" do %>
  <%= link_to candidato_path(candidato), class:"link-candidato" do %>
    <div class="text-center mt-2">
        <%= cl_image_tag candidato.photo.key, :transformation=>[
      {:radius=>"max"},
      {:height=>150, :crop=>"scale"}
      ] %>
    </div>
  <% end %>

  <div class="card-candidato-infos">
    <div class="d-flex align-items-start justify-content-between">
      <h2 class="pr-4"><%= candidato.nome_urna %></h2>

      <% if user_signed_in? %>
        <% if current_user.candidatos.include? candidato %>
          <% marcado = current_user.marcados.find_by(candidato_id: candidato.id) %>
          <% if marcado.desativado == true %>
            <%= link_to marcado_path(marcado), method: :patch, remote: true  do %>
              <i class="fas fa-thumbtack pin-cinza"></i>
            <% end %>
          <% else %>
            <%= link_to marcado_path(marcado), method: :patch, remote: true  do %>
              <i class="fas fa-thumbtack pin-amarelo"></i>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to candidato_marcados_path(candidato), method: :post, remote: true  do %>
            <i class="fas fa-thumbtack pin-cinza"></i>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to "", data: { toggle: "modal", target: "#exampleModalCenter" } do %>
          <i class="fas fa-thumbtack pin-cinza"></i>
        <% end %>
      <% end %>
    </div>

    <p class="mt-2 mb-3"><i class="fas fa-user-tie"></i> <strong><%= candidato.cargo %></strong></p>

    <div class="d-flex justify-content-between align-items-baseline card-bottom">
      <p><%= candidato.estado %></p>
      <h2 class="card-candidato-pricing"><%= candidato.partido %></h2>
    </div>
  </div>
</div>

<div class="modal fade log-modal" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <%= render "shared/login_modal" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
  Eleição não é um evento banal, é um processo democrático e contínuo
  que exige máxima consciência e responsabilidade de seus cidadãos. © 2021 by:
  <a href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=contato@repolitiks.me" target="_blank">REPOLITIKS</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_login_modal.html.erb
<div class="modal-dialog modal-dialog" role="document">
  <div class="modal-content py-1">
    <div class="modal-header py-1 px-4 align-items-center text-center">
      <h3 class="modal-title flex-grow-1" id="exampleModalCenterTitle">
        <p class="logo-font mb-0"><span class="logo-decrescendum logo-border-right logo-small pr-1">RE</span><span class="logo-decrescendum logo-small pl-1">PLTKS</span></p>
      </h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body px-2 py-2">
      <%# navtab %>
      <div class="container pl-0 pr-0">
        <div class="card">
          <div class="card-header px-4">
            <ul class="nav nav-pills card-header-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" id="entrar-tab" data-toggle="tab" href="#entrar" role="tab" aria-controls="entrar" aria-selected="true">Entrar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="cadastro-tab" data-toggle="tab" href="#cadastro" role="tab" aria-controls="cadastro" aria-selected="false">Cadastrar-se</a>
              </li>
            </ul>
          </div>

          <div class="tab-content" id="myTabContent">
            <%# <h2 class="card-title text-center mt-3">Entrar/Cadastrar</h2> %>
            <div class="tab-pane fade show active" id="entrar" role="tabpanel" aria-labelledby="home-tab">
              <%# login form %>
              <div class="py-2 px-3">
                <%= simple_form_for(@user_login, url: user_session_path, remote: true) do |f| %>
                  <%= f.error_notification %>
                  <div class="form-inputs">
                      <%= f.input :email,
                                  required: false,
                                  autofocus: true,
                                  input_html: { autocomplete: "email", class: "input-modal" } %>
                      <%= f.input :password, label: "Senha",
                                  required: false,
                                  input_html: { autocomplete: "current-password", class: "input-modal" } %>
                      <%= f.input :remember_me, label: "Mantenha-me conectado", as: :boolean if devise_mapping.rememberable? %>
                  </div>
                  <div class="form-actions">
                    <%= f.button :submit, "Entrar",  class: "btn btn-dark w-100 mb-2" %>
                  </div>
                <% end %>
                <%= link_to "Esqueceu sua senha?", new_password_path(resource_name), class: "link-modal" %><br />
                <hr>
                <p class="m-0" style="color: #E67E22; font-size: 14px;">Não possui uma conta? Clique em "Cadastrar-se".</p>
              </div>
            </div>
            <div class="tab-pane fade" id="cadastro" role="tabpanel" aria-labelledby="cadastro-tab">
              <%# sign up form %>
              <div class="py-2 px-3">
                <%# <%= simple_form_for(@user_sign_up, url: user_registration_path, remote: true) do |f| %>
                <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), remote: true) do |f| %>
                  <%# <%= f.error_notification %>
                  <div class="errors" style="color: red; font-size: 18px"></div>
                  <div class="form-inputs">
                    <%= f.input :nome,
                                required: true,
                                autofocus: true,
                                input_html: { autocomplete: "nome", class: "input-modal" } %>
                    <%= f.input :email,
                                required: true,
                                autofocus: true,
                                input_html: { autocomplete: "email", class: "input-modal" } %>
                    <%= f.input :password, label: "Senha",
                                required: true,
                                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                                input_html: { autocomplete: "new-password", class: "input-modal" } %>
                    <%= f.input :password_confirmation, label: "Confirmar senha",
                                required: true,
                                input_html: { autocomplete: "new-password", class: "input-modal" } %>
                  </div>
                  <div class="form-actions">
                    <%= f.button :submit, "Cadastrar",  class: "btn btn-dark w-100 mb-2" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="pt-2 pb-1 d-flex">
          <%# <%= link_to "Cadastrar-se", new_registration_path(resource_name), class: "btn btn-success" %>
          <button type="button" class="btn btn-secondary ml-auto mr-0" data-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-5">

  <%= link_to root_path, class: "navbar-brand py-0" do %>
    <p class="text-logo logo-font mb-0"><span class="logo-fading logo-border-right pr-1">RE</span><span class="logo-decrescendum pl-1">PLTKS</span></p>
  <% end %>

  <button class="navbar-toggler py-0 my-1 px-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <%# Search field %>
      <% unless current_page?(root_path) %>
        <%= render "shared/search_field" %>
      <% end %>

      <%# Link Políticos %>
      <%= link_to "Políticos", candidatos_path, class: "nav-link mr-2" %>
      <% if user_signed_in? %>
        <%# Casinha Home %>
        <li class="nav-item">
          <%= link_to user_root_path, class:"nav-link mr-3" do %>
            <i class="fas fa-house-user nav-casinha"></i>
          <% end %>
        </li>
        <%# Avatar dropdown %>
        <li class="nav-item dropdown">
          <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p><%= current_user.email %></p>
            <%= link_to "Minha conta", edit_user_registration_path, class: "dropdown-item item-minha-conta" %>
            <hr class="m-2">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%# Link Entrar %>
          <%= link_to "Entrar", "", data: { toggle: "modal", target: "#exampleModalCenter" } , class: "nav-link nav-login rounded" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="modal fade log-modal" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <%= render "shared/login_modal" %>
</div>

app/views/shared/_search_bar.html.erb
<%# <div class="container" style="height: 10px;"></div> %>

<div id="search-bar-container" class="search-bar-container rounded">
  <%= form_tag candidatos_path, method: :get, class:"d-flex" do %>
    <div id="search-bar" class="search-bar sticky-top rounded row px-1 py-1 justify-content-center align-items-center mx-auto shadow-sm">
      <div class="d-flex flex-column rounded group-pad group-width">
        <small><%= label_tag :nome, nil, class: 'm-0 label-border-pad' %></small>
        <%= text_field_tag :nome, params[:nome], placeholder: "Nomes...", class: 'search-input input-border-pad' %>
      </div>
      <div class="search-middle-border"></div>
      <div class="d-flex flex-column rounded group-pad group-width">
        <small><%= label_tag :cargo, nil, class: 'm-0 label-border-pad' %></small>
        <%= text_field_tag :cargo, params[:cargo], placeholder: "Cargos...", class: 'search-input input-border-pad' %>
      </div>
      <div class="search-middle-border"></div>
      <div class="d-flex flex-column rounded group-pad group-width">
        <small><%= label_tag :partido, nil, class: 'm-0 label-border-pad' %></small>
        <%= text_field_tag :partido, params[:partido], placeholder: "Siglas...", class: 'search-input input-border-pad' %>
      </div>
      <div class="search-middle-border"></div>
      <div class="d-flex flex-column rounded group-pad group-width">
        <small><%= label_tag :estado, nil, class: 'm-0 label-border-pad' %></small>
        <%= select_tag :estado, options_for_select(Candidato::ESTADOS, params[:estado]), prompt: "Todos", class: "search-input select-gray select-border-pad rounded" %>
      </div>
      <%# <div class="search-middle-border"></div> %>
      <%# <div class="d-flex flex-column rounded group-pad group-width"> %>
        <%# <small><%= label_tag :eleito, "Eleito?", class: 'm-0 label-border-pad' %>
        <%# <%= select_tag :eleito, options_for_select(["Sim", "Não"], params[:eleito]), prompt: "Todos", class: "search-input select-gray select-border-pad rounded" %>
      <%# </div> %>
      <div class="search-btn-margin">
        <%= button_tag(type: "submit", class: "btn btn-dark search-btn-size") do %>
          <i class="fas fa-search"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_search_field.erb
<div class="d-flex align-items-center py-1 mr-3">
  <%# Barra de busca %>
  <%= form_tag candidatos_path, method: :get do %>
    <div class="search-field-form">
      <%= text_field_tag :query, params[:query], placeholder: "Busca...", class: 'search-field-input w-100 h-100 bg-white pl-3 pr-5 ' %>
      <button type="submit" name="commit" class="search-field-btn"><i class="fas fa-search"></i></button>
    </div>
  <% end %>

  <%# Botão de + %>
  <%= link_to "", data: { toggle: "modal", target: "#searchModal" } , class: "search-field-plus" do %>
    <i class="fas fa-plus"></i>
  <% end %>
</div>

<%# Modal para o botão de + %>
<div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModalTitle" aria-hidden="true">
  <%# render "shared/search_modal" %>
  <div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header py-2s">
      <h3 class="modal-title mx-auto" id="searchModalTitle">Busca detalhada</h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="modal-body py-1">

      <%# <div class="rounded"> %>
        <%= form_tag candidatos_path, method: :get, class:"d-sm-flex align-items-center" do %>
          <div class="rounded px-3 py-1 mb-2 justify-content-center align-items-center shadow-sm">
            <div class="d-flex align-items-center">
              <div class="d-flex flex-column rounded group-pad group-width">
                <small><%= label_tag :nome, nil, class: 'm-0 label-border-pad' %></small>
                <%= text_field_tag :nome, params[:nome], placeholder: "Nomes...", class: 'input-border-pad' %>
              </div>
              <div class="search-middle-border"></div>
            </div>
            <div class="d-flex align-items-center">
              <div class="d-flex flex-column rounded group-pad group-width">
                <small><%= label_tag :cargo, nil, class: 'm-0 label-border-pad' %></small>
                <%= text_field_tag :cargo, params[:cargo], placeholder: "Cargos...", class: 'input-border-pad' %>
              </div>
              <div class="search-middle-border"></div>
            </div>
            <div class="d-flex align-items-center">
              <div class="d-flex flex-column rounded group-pad group-width">
                <small><%= label_tag :partido, nil, class: 'm-0 label-border-pad' %></small>
                <%= text_field_tag :partido, params[:partido], placeholder: "Siglas...", class: 'input-border-pad' %>
              </div>
              <div class="search-middle-border"></div>
            </div>
            <div class="d-flex align-items-center group-select-width">
              <div class="d-flex flex-column rounded group-pad group-width">
                <small><%= label_tag :estado, nil, class: 'm-0 label-border-pad' %></small>
                <%= select_tag :estado, options_for_select(Candidato::ESTADOS, params[:estado]), prompt: "Todos", class: "select-gray select-border-pad rounded" %>
              </div>
            </div>
            <%# <div class="search-middle-border"></div> %>
            <%# <div class="d-flex flex-column rounded group-pad group-width"> %>
              <%# <small><%= label_tag :eleito, "Eleito?", class: 'm-0 label-border-pad' %>
              <%# <%= select_tag :eleito, options_for_select(["Sim", "Não"], params[:eleito]), prompt: "Todos", class: "search-input select-gray select-border-pad rounded" %>
            <%# </div> %>
            <%# <div class="search-btn-margin"> %>
              <%# <%= button_tag(type: "submit", class: "btn btn-dark search-btn-size") do %>
                <%# <i class="fas fa-search"></i> %>
              <%# <% end %>
            <%# </div> %>
          </div>
          <div class="search-btn-margin">
            <%= button_tag(type: "submit", class: "btn btn-dark search-btn-size ml-4 my-2 ") do %>
              <i class="fas fa-search"></i>
            <% end %>
          </div>
        <% end %>
      <%# </div> %>
    </div>
  </div>
</div>









</div>

app/views/shared/_search_modal.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">

    <div class="modal-header">
      <h3 class="modal-title" id="searchModalTitle"> </h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="modal-body">

      <% render "shared/search_bar" %>

    </div>
  </div>
</div>